### ISSUE TITLE
Deployment to any subdirectories (e.g. by adding hash routing)

### ISSUE THREAD

**Issue by kachkaev** [remorses/dokz#1]
Hi @remorses, I'm really glad to discover dokz, great work! 🙌

My teammates and I have been using `docz` for a while and unfortunately we’re stuck with version `0.13.x`, because `docz` v1 and v2 do not support hash routing: https://github.com/doczjs/docz/issues/763

Because of that, we cannot deploy our docs to a subdirectory, because the build artifact wrongly expect that our `index.html` will be at `example.com` and not at `example.com/whatever/`.

The solution is blocked by https://github.com/gatsbyjs/gatsby/issues/14161.

As of today https://github.com/doczjs/docz/issues/763 is the [number one docz bug by the number of 👍](https://github.com/doczjs/docz/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). Wondering if we could solve that problem with Next under the hood anyhow, which can give dokz an initial flow of users?

WDYT?

**Comment by kachkaev** [comment]
Thanks for your reply @remorses!

I tried `basePath: '/subpath'` as you suggested and it allowed me to see the content at different URLs. However, that does not solve the problem described in https://github.com/doczjs/docz/issues/763

The solution I’m looking for would involve something like ` basePath: '.'`, which is currently not possible in Next.js apps. The main goal is to produce an artifact that can then be deployed to any directory without a need to rebuild. See https://create-react-app.dev/docs/deployment/#serving-the-same-build-from-different-paths that describes this use case in CRA.

The reason for deploying to any subdirectory is that the same artifact will go through several stages. First, you'll want to see your doc at `https://example.com/docs/preview/my-doc/a41c298b/` and then at `https://example.com/docs/my-doc/`, once it's signed off. Subdomains would be ideal here, but it's not always possible because you want all your deployed static files to share auth cookie etc.

At our company, we do use Next.js and the deployment to arbitrary subdirectories works, but for that we need to use hash-based routing inside all apps and stick with only one Next.js page per app.

It'd be great if dokz could have a hash routing mode, i.e. include only one Next.js page and serve different documents at `localhost:3003/#/whatever`, that would make the build artifact deployable to any server dir. Besides, it would allow dokz to discoverer md(x) documents not just in the pages dir, but anywhere else in the package. This is very useful for documenting packages that may contain something like

```txt
[package-dir]/src/components/Button.tsx
[package-dir]/src/components/Button.mdx
```

**Comment by remorses** [comment]
Dokz doesn't do anything special, it uses nextjs to serve mdx files as any other page, i once tried to deploy a nextjs in a subdirectory and it didn't work because nextjs serves static files at the root of the domain

**Comment by kachkaev** [comment]
Let me check our teams’ code next week. We’ve created a company-wide next plugin, which allows us to overcome this issue. Next.js `<Link />` don't work hence we can't have several pages in each app, however, all css and js resources are available regardless of the base dir to which we deploy build artifacts.

**Comment by kachkaev** [comment]
Right so it turns out we make it possible to deploy next SPAs to subdirs via this Next.js config:

```
{
    // Ensure the app works when deployed to a subdirectory
    assetPrefix: ".",
}
```

It's a part of next plugin shared between all company apps – that's why I could not recall the trick easily.

This means that it could be possible to run dokz in an arbitrary subdirectly given that:

* `assetPrefix: "."`
* There's only one file in pages (index page)
* md(x) files are discoverable not via the next pages mechanism, but by some custom server maybe
* on build, each mdx page becomes a resource, which index.tsx page can load based on the route in the hash
* Next.js Link tags are replaced with some hash-based Link implementation
