### ISSUE TITLE
Dokz 1.0.30 breaks Landing Blocks on Safari

### ISSUE THREAD

**Issue by crubier** [remorses/dokz#10]
I have a website that combine Landing Blocks and Dokz in a single nextjs intance.

With Dokz 1.0.29 the statically extracted landing page looks like this in Safari:

https://5ee22377d3f54bed49b934e2--labs-sterblue-com.netlify.app

![Screenshot 2020-06-18 at 18 57 51](https://user-images.githubusercontent.com/2954572/85055675-d4673b00-b195-11ea-83cd-eed44f3ab385.jpg)

Then without changing anyting else, moving Dokz to 1.0.30, the landing page looks like this:

https://5eea4dd7445a8b01dd86992d--labs-sterblue-com.netlify.app

![Screenshot 2020-06-18 at 18 55 37](https://user-images.githubusercontent.com/2954572/85055745-f6f95400-b195-11ea-8047-5bb232dd4cf1.jpg)

I suspect this might be linked to a version change of `layout-kit-react` maybe?

**Comment by remorses** [comment]
This is fixed in the last `dokz` version, I was using a `height: 100%` on a container element, it seems that safari treats that `height` property relative to the window size, chrome does not

This problem wasn't visible using dokz alone because dokz has always height lower than the window height
