### ISSUE TITLE
Props?

### ISSUE THREAD

**Issue by pierrenel** [remorses/dokz#11]
Great work!

In Docz, there's a way to see the prop-types a component uses, ie 

```
<Props of={Button} />
```

Are there plans for this sort of functionality? Then I can move away from Storybook hurrah!

**Comment by remorses** [comment]
If you are using Vscode this is a issue with the mdx extension, the progress is tracked here https://github.com/mdx-js/vscode-mdx/issues/56

I have already replaced storybook with dokz, the fact that there is no auto completion makes me memorize the prop names 🤣

**Comment by pierrenel** [comment]
Heh no I just want a list of the proptypes of a component in Dokz, ie below the Playground. I think storybook has this too.
