### ISSUE TITLE
Sidebar scroll behavior

### ISSUE THREAD

**Issue by mervinjin** [remorses/dokz#17]
Sidebar will scroll to top when clicked,  it's unexpected.

<a href="https://www.loom.com/share/5b21f20e958449638acc854cf60e9df7">  <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/5b21f20e958449638acc854cf60e9df7-1593190889870-with-play.gif"> </a>

**Comment by remorses** [comment]
This is because the page wrapper component is remounted when you click a link, unfortunately it depends on the `@mdx/react` package

**Comment by mervinjin** [comment]
Maybe we could make `NavBar`、`SideNav` isolated from MDXProvider ?

They do not have a close relationship with mdx and should be isolated.

```tsx
export function DokzProvider({ children, ...rest }: DokzProviderProps) {
	const ctx = { ...defaultDokzContext, ...rest }
	const { mdxComponents: userMDXComponents = {}, initialColorMode } = ctx

	const index = getMdxSidebarTree()

	return (
		// TODO merge configs
		<DokzContext.Provider value={ctx}>
			<ColorModeProvider value={initialColorMode}>
				<SideNav
					alignSelf="flex-start"
					position="fixed"
					top={NAVBAR_H}
					bottom={0}
					fontSize="0.9em"
					// fontWeight='500'
					// left={0}
					tree={index}
					// height='100%'
					width={SIDENAV_W}
					display={['none', null, 'block']}
					overflowY="auto"
					overflowX="hidden"
				/>
				<MDXProvider components={{ ...MDXComponents, ...userMDXComponents }}>{children}</MDXProvider>
			</ColorModeProvider>
		</DokzContext.Provider>
	)
}
```

**Comment by mervinjin** [comment]
I can do some works if need.

**Comment by remorses** [comment]
No because this way it would wrap every page with the sidebar, now it only wraps `mdx` and `md` pages

This could be probably fixed in `@mdx-js/react`

**Comment by mervinjin** [comment]
Okay.
