### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by hunvreus** [remorses/dokz#19]
There's currently no license in this repo.

I'd like to understand if this can be safely used for Open Source and commercial projects.

**Comment by remorses** [comment]
The license is MIT, I will add a license file

In the next months I will also launch a pro integration with additional features 
- search
- most read docs analytics 
- user feedback
- most hated/loved docs analytics 
- edit this doc button with automatic pull request opening

Let me know if you have any additional feature you would like to see

**Comment by hunvreus** [comment]
Thanks @remorses.

I'm looking at adding search with [Lunr.js](https://lunrjs.com/) and will port over a component to display API references from an Open API v3 file (aka Swagger).

**Comment by remorses** [comment]
Is there a feature you would pay for? I am trying to monetize this project to make it more sustainable
