### ISSUE TITLE
Index route 404

### ISSUE THREAD

**Issue by imdongchen** [remorses/dokz#20]
## Current behavior 

Clicking on the ~~`index.html`~~ `index.mdx` doc goes to `/index`. This will result in 404 in trailing slash config because it will redirect to `/index/`, which resolves to `/index/index.html`.

## Expected behavior
Clicking on the ~~`index.html`~~ `index.mdx` doc should go to `/`. 

## Suggestion to fix

I think this code snippet is supposed to solve the problem: https://github.com/remorses/dokz/blob/master/dokz/src/plugin/getMdxFilesIndex.ts#L44-L47, but it should be

```js
    // replace `index` with empty string
    relativePath.replace(/^index$/, '')

    // remove this line
    // relativePath = relativePath || '/'
    return '/' + relativePath
}
```

Let me know what you think and I'm happy to send a PR

**Comment by remorses** [comment]
I don’t understand where the index.html path comes from, can you try remove the HTML extension?

Where is this index.html file, in the public directory or pages directory?

**Comment by imdongchen** [comment]
I have one deployed here https://imdongchen.github.io/dokz/. Try clicking `Get started` and you'll see 404

**Comment by remorses** [comment]
Try with the latest version

The regex was not removing the `index` url because assumed it would always be `/index`, that's not the case

**Comment by imdongchen** [comment]
Nice! It works! Thank you for the great work!!
