### ISSUE TITLE
Allow for custom darkmode switch

### ISSUE THREAD

**Issue by BjoernRave** [remorses/dokz#31]
I would like to define a custom darkmode switch, so I can control switching to dark mode myself, as I need to show a different logo depending on which mode I am in

**Comment by remorses** [comment]
You can already do that, use this component as an example

https://github.com/remorses/dokz/blob/eb08f69d60398e3746ded4ff3b9ae5f9cefe66e7/dokz/src/components/NavBar.tsx#L38

**Comment by BjoernRave** [comment]
ah nice, might be nice to mention that in the docs :)

**Comment by remorses** [comment]
ok
