### ISSUE TITLE
Use full space for right sidebar

### ISSUE THREAD

**Issue by BjoernRave** [remorses/dokz#33]
The right sidebar, which shows all the subheaders, when being used on a 1920x1080p screen is not using all the space it has available, because there is a fixed witdth of `200px` defined. 

When removing it the size of the box changes per page, which is maybe not desirable.

If you want I can try to make a PR for that

**Comment by remorses** [comment]
on ultra wide screens it would look weird, i can make it larger on larger screen but not full width

**Comment by BjoernRave** [comment]
why would it look weird on ultra wide screens? 

it just allows to show the whole struture of the page.

Just to clarify I am talking about this section:

[
![Screenshot 2020-09-18 at 19 25 44](https://user-images.githubusercontent.com/36173920/93627170-0b86fb80-f9d4-11ea-9b0f-fb17f7bbac6b.png)
](url)

**Comment by remorses** [comment]
Ok, i understood the wrong sidebar
