### ISSUE TITLE
Generating the static pages - no sidebar

### ISSUE THREAD

**Issue by miroslav93** [remorses/dokz#45]
When using `next export`, it is possible to export the static pages to the "root/out" directory with no issues, however, the sidebar is nowhere to be found.
Is it possible to have Dokz include the sidebar when exporting somehow?

**Comment by remorses** [comment]
Do you want to have the sidebar json file available in the server?

**Comment by miroslav93** [comment]
I managed to get this resolved actually, shortly after reporting. The way I approached this originally was by opening the index.html generated, thinking I could see all the features there, but when I tried using `npx server` on the "out" folder, it generated everything locally.
The sidebar still has a miniscule delay in the output files, but other than that, this works fantastic. This really is a great tool, I will see if my organization can endorse it somehow.
