### ISSUE TITLE
Throws "Invalid Hook Call" on init

### ISSUE THREAD

**Issue by ensorep** [remorses/dokz#54]
when creating a project via `npm init dokz-app` the follow is generated when spinning up a dev server (`npm run dev`)

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/20014093/138541191-431bf66a-7f30-4e37-9177-3e576a501a7c.png">

Working in a new directory, with nothing but an `npm i` command run previously.

**Comment by remorses** [comment]
It should be fixed now
