### ISSUE TITLE
<ul> styling

### ISSUE THREAD

**Issue by adriandmitroca** [remorses/dokz#7]
Lists aren't styled too well imho, do you think there's any space for an improvements?

There's a huge whitespace between last paragraph (usually title) and the list itself.

![Pasted_Image_07_06_2020__01_14](https://user-images.githubusercontent.com/3842935/83956264-66994600-a85c-11ea-95a3-8ae09727d4eb.png)

**Comment by remorses** [comment]
Yes i will change the list look, fo you have any design you like to take inspiration from?

I was thinking to do something similar to this blog https://joshwcomeau.com/react/animated-sparkles-in-react/

**Comment by adriandmitroca** [comment]
Looks good!

**Comment by remorses** [comment]
I changed the styling, you can change the icon used via the `listItemIcon` prop passing a component

![Schermata 2020-06-08 alle 13 33 15](https://user-images.githubusercontent.com/31321188/84028025-466aa380-a990-11ea-8b5f-7ffdcec2988b.png)
