### ISSUE TITLE
MDX List rendering is wrong

### ISSUE THREAD

**Issue by crubier** [remorses/dokz#9]
This code in Dokz:

![Screenshot 2020-06-17 at 14 35 44](https://user-images.githubusercontent.com/2954572/84904955-e10d6580-b0a7-11ea-90b0-baaa73a93f40.jpg)

Renders to this:

![Screenshot 2020-06-17 at 14 35 30](https://user-images.githubusercontent.com/2954572/84904972-e9fe3700-b0a7-11ea-9446-48ccd44a7f55.jpg)

But on a normal markdown renderer like github, this code:

```
And here is a numbered list:

1. Coucou
2. Toutou

And a nested bulleted list:

  - Lol Lol Lol Lol Lol Lol
    - Lol Lol Lol Lol Lol Lol
    - Yup Yup Yup Yup Yup Yup
      - Lol Lol Lol Lol Lol Lol
    - Yup Yup Yup Yup Yup Yup
  - Yup Yup Yup Yup Yup Yup
    - Lol Lol Lol Lol Lol Lol
      - Lol Lol Lol Lol Lol Lol
      - Yup Yup Yup Yup Yup Yup
    - Lol Lol Lol Lol Lol Lol
    - Yup Yup Yup Yup Yup Yup
  - Yup Yup Yup Yup Yup Yup
```

Should render to this:

And here is a numbered list:

1. Coucou
2. Toutou

And a nested bulleted list:

  - Lol Lol Lol Lol Lol Lol
    - Lol Lol Lol Lol Lol Lol
    - Yup Yup Yup Yup Yup Yup
      - Lol Lol Lol Lol Lol Lol
    - Yup Yup Yup Yup Yup Yup
  - Yup Yup Yup Yup Yup Yup
    - Lol Lol Lol Lol Lol Lol
      - Lol Lol Lol Lol Lol Lol
      - Yup Yup Yup Yup Yup Yup
    - Lol Lol Lol Lol Lol Lol
    - Yup Yup Yup Yup Yup Yup
  - Yup Yup Yup Yup Yup Yup

**Comment by remorses** [comment]
Added new list features in version `1.0.35`

![Schermata 2020-06-18 alle 20 24 53](https://user-images.githubusercontent.com/31321188/85058169-01214f80-b1a2-11ea-931c-3b87bc0499c8.png)


The internal list type is not super pretty, let me know if you find a better icon

**Comment by crubier** [comment]
👍 Excellent it works !
